name: jasmine_header_fix
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bcftools=1.22
  - bioconda::coreutils=8.25
  - bioconda::htslib=1.22.1
  - conda-forge::awk=20250116
  - conda-forge::bash=5.2.37
