---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bcftools=1.22
- bioconda::coreutils=8.25
- conda-forge::gawk=5.3.1
- conda-forge::gzip=1.14
- conda-forge::jq=1.8.1
- conda-forge::python=3.13.0
